### ISSUE TITLE
关键词与摘要连在一起的问题

### ISSUE THREAD

**Issue by mb-Ma** [Sophie10001b/swjtuThesisV3.0#14]
请问，“关键词“ 三个字会出现在摘要正文文本之后，中间没有换行。该问题如何解决。

![image](https://github.com/user-attachments/assets/c285b5a6-53ce-4983-a23c-d40c17818335)

**Comment by Sophie10001b** [comment]
感谢提交issue！该问题由摘要正文输入中未手动换行导致：
\cabstract
{
这里是中文摘要输入区。
}
{关键词1，关键词2，关键词3，关键词4，关键词5}

需要更改为：
\cabstract
{
这里是中文摘要输入区。
% 这里手动换行
}
{关键词1，关键词2，关键词3，关键词4，关键词5}

目前更新后的版本在相关命令中额外添加了最后的换行，解决了由于未手动换行导致的关键字同行问题~

**Comment by mb-Ma** [comment]
感谢回复，已解决 \thumbs
