### ISSUE TITLE
关于每行字数的问题

### ISSUE THREAD

**Issue by yexianyao** [Sophie10001b/swjtuThesisV3.0#17]
大佬您好，我发现模板中每行算上字符只有35个，正常应该是37个才对，需要怎么解决呀？去年我旁听时有学长因为这个问题答辩直接没过
![image](https://github.com/user-attachments/assets/d4c1d1cd-adc0-46b0-ade9-c7fc44c4f96f)
这是您的模板的效果
![image](https://github.com/user-attachments/assets/fd6b46a7-615d-47e1-a382-82ba2f57a2e0)

**Comment by yexianyao** [comment]
我才看到学校出了新的模板，大佬的格式应该是对的

**Comment by Sophie10001b** [comment]
新的模板上面没有具体规定每行字数，我是直接用字完整填充一行后数出来是35字每行(无标点)，之前老模板下我反正在格式上没被挑问题，至于新模板的话，如果到时候被指出问题还请麻烦在这里提一下🤔
