### ISSUE TITLE
字体编译不通过

### ISSUE THREAD

**Issue by mb-Ma** [Sophie10001b/swjtuThesisV3.0#3]
直接将现有源码下载，解压到overleaf，在编译main.tex出现cls文件中字体加载不成功、编译不通过的问题。具体报错信息如下：
请问有什么方法解决？
--------------------------------------------------------------
l.47 \setCJKmainfont
                    [BoldFont=SimHei]{SimSun}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

l.48 \setCJKfamilyfont
                      {zhsong}{SimSun}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

l.49 \setCJKfamilyfont
                      {zhhei}{SimHei}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

(/usr/local/texlive/2023/texmf-dist/tex/latex/geometry/geometry.sty
Package: geometry 2020/01/02 v5.9 Page Geometry
(/usr/local/texlive/2023/texmf-dist/tex/generic/iftex/ifvtex.sty
Package: ifvtex 2019/10/25 v1.7 ifvtex legacy package. Use iftex instead.

**Comment by Sophie10001b** [comment]
因为兼容性问题，3.0版本里的字体设置由直接通过读取ctexbook在windows下的字体更改为手动设置字体，因此在overleaf上有可能会存在字体名不匹配的问题(或者是字体缺失？)，可能的解决方法需要你自己手动下载宋体(SimSun)和黑体(SimHei)的字体文件并与`main.tex`放在一起，之后在`swjtuThesis.cls`中将：

> \setCJKmainfont[BoldFont=SimHei]{SimSun}
> \setCJKfamilyfont{zhsong}{SimSun}
> \setCJKfamilyfont{zhhei}{SimHei}

中的`SimSun`与`SimHei`更改为你下载好的字体文件的名称(一般都是这个名字)，或者在windows下直接把：

> \setCJKmainfont[BoldFont=SimHei]{SimSun}
> \setCJKfamilyfont{zhsong}{SimSun}
> \setCJKfamilyfont{zhhei}{SimHei}
> \NewDocumentCommand \songti {}{\CJKfamily{zhsong}}
> \NewDocumentCommand \heiti {}{\CJKfamily{zhhei}}

注释或删掉，之后将

> \LoadClass[UTF8,nofonts,fntef,fancyhdr,a4paper,cs4size]{ctexbook}

中的`nofonts`更改为`winfonts`，这样就能直接读取默认的字体设置，但是在overleaf上这玩意也会报错，因此需要把`nofonts`直接删掉才能编译通过，代价是编译出来的字体与要求不太匹配(主要是标题没用黑体)，再加上学位论文这种大项目在overleaf上很容易编译超时，因此我个人还是比较建议在本地进行编译。。。

**Comment by mb-Ma** [comment]
感谢！已经下载所有字体，这个问题是解决了。确实容易timeout, 且会在\makecover上报错。

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/23/2024 23:36 |
| To | ***@***.***> |
| Cc | Minbo ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Sophie10001b/swjtuThesisV3.0] 字体编译不通过 (Issue #3) |

因为兼容性问题，3.0版本里的字体设置由直接通过读取ctexbook在windows下的字体更改为手动设置字体，因此在overleaf上有可能会存在字体名不匹配的问题(或者是字体缺失？)，可能的解决方法需要你自己手动下载宋体(SimSun)和黑体(SimHei)的字体文件并与main.tex放在一起，之后在swjtuThesis.cls中将：

\setCJKmainfont[BoldFont=SimHei]{SimSun}
\setCJKfamilyfont{zhsong}{SimSun}
\setCJKfamilyfont{zhhei}{SimHei}

中的SimSun与SimHei更改为你下载好的字体文件的名称(一般都是这个名字)，或者在windows下直接把：

\setCJKmainfont[BoldFont=SimHei]{SimSun}
\setCJKfamilyfont{zhsong}{SimSun}
\setCJKfamilyfont{zhhei}{SimHei}
\NewDocumentCommand \songti {}{\CJKfamily{zhsong}}
\NewDocumentCommand \heiti {}{\CJKfamily{zhhei}}

注释或删掉，之后将

\LoadClass[UTF8,nofonts,fntef,fancyhdr,a4paper,cs4size]{ctexbook}

中的nofonts更改为winfonts，这样就能直接读取默认的字体设置，但是在overleaf上这玩意也会报错，因此需要把nofonts直接删掉才能编译通过，代价是编译出来的字体与要求不太匹配(主要是标题没用黑体)，再加上学位论文这种大项目在overleaf上很容易编译超时，因此我个人还是比较建议在本地进行编译。。。

**Comment by Sophie10001b** [comment]
能编译出pdf吗，我这边目前在overleaf上复现的结果是在手动引入字体后能够正常编译，同时免费版在仅编译模板的情况下并不会timeout，如果报错影响编译的话，是否方便提供报错信息呢？

**Comment by mb-Ma** [comment]
模板也没能编译，下面是报错信息：

Undefined control sequence.

 
‪./main.tex, 23‬
The compiler is having trouble understanding a command you have used. Check that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \usepackage{...}.
[Learn more](https://www.overleaf.com/learn/Errors/Undefined_control_sequence)
\fillinblank #1#2->\CJKunderline 
                                 {\makebox [#1]{#2}}
l.23 \makecover
             
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by mb-Ma** [comment]
即使装了字体，必须在LuaHBTeX编译模式下进行，常用的pdflatex，还是在字体那里编译不通过。

**Comment by Sophie10001b** [comment]
目前在latex里使用中文，或者说基于cjk来支持中文排版时一般会需要使用xeLaTeX来进行编译，这样会默认使用utf-8进行编码，如果使用lua或pdf的话可能得手动设置utf-8编码才能正常编译（

**Comment by mb-Ma** [comment]
xeLaTeX可以work，当前能够编译。感谢！:-)
