### ISSUE TITLE
封面需要加一下空格

### ISSUE THREAD

**Issue by huajunge** [Sophie10001b/swjtuThesisV3.0#4]
封面的“西南交通大学研究生学位论文”需要调整一下间距
修改：swjtuThesis.cfg
\def\cover@cSchool{\hspace{0.4em}西\hspace{0.5em}南\hspace{0.5em}交\hspace{0.5em}通\hspace{0.5em}大\hspace{0.5em}学}
\def\cover@eSchool{Southwest Jiaotong University}
\def\cover@cThesis{\hspace{0.5em}研\hspace{0.5em}究\hspace{0.5em}生\hspace{0.5em}学\hspace{0.5em}位\hspace{0.5em}论\hspace{0.5em}文}

**Comment by Sophie10001b** [comment]
感谢提交issue！最新版本已经调整了封面标题的间距设置
